"""creation des 7 tables

Revision ID: 743af3148355
Revises: 
Create Date: 2026-07-16 00:04:27.598177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743af3148355'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id_destination', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('gouvernorat', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='chk_dest_lat'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='chk_dest_lon'),
    sa.PrimaryKeyConstraint('id_destination')
    )
    op.create_table('station',
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('gouvernorat', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='chk_station_lat'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='chk_station_lon'),
    sa.PrimaryKeyConstraint('id_station')
    )
    op.create_table('chauffeur',
    sa.Column('id_chauffeur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('statut', sa.String(length=10), nullable=False),
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.CheckConstraint("statut IN ('actif','conge','maladie')", name='chk_chauf_statut'),
    sa.ForeignKeyConstraint(['id_station'], ['station.id_station'], ),
    sa.PrimaryKeyConstraint('id_chauffeur')
    )
    op.create_table('lot',
    sa.Column('id_lot', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('priorite', sa.String(length=10), nullable=False),
    sa.Column('fragile', sa.Boolean(), nullable=False),
    sa.Column('caisson_requis', sa.String(length=15), nullable=False),
    sa.Column('id_destination', sa.Integer(), nullable=False),
    sa.CheckConstraint("caisson_requis IN ('standard','refrigere','securise')", name='chk_lot_caisson'),
    sa.CheckConstraint("priorite IN ('haute','moyenne','basse')", name='chk_lot_prio'),
    sa.CheckConstraint('volume > 0', name='chk_lot_vol'),
    sa.ForeignKeyConstraint(['id_destination'], ['destination.id_destination'], ),
    sa.PrimaryKeyConstraint('id_lot')
    )
    op.create_table('vehicule',
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('capacite', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('assurance', sa.Boolean(), nullable=False),
    sa.Column('statut', sa.String(length=12), nullable=False),
    sa.Column('type_caisson', sa.String(length=15), nullable=False),
    sa.Column('id_station', sa.Integer(), nullable=False),
    sa.CheckConstraint("statut IN ('actif','reserve','hors_service')", name='chk_veh_statut'),
    sa.CheckConstraint("type_caisson IN ('standard','refrigere','securise')", name='chk_veh_caisson'),
    sa.CheckConstraint('capacite > 0', name='chk_veh_cap'),
    sa.ForeignKeyConstraint(['id_station'], ['station.id_station'], ),
    sa.PrimaryKeyConstraint('id_vehicule')
    )
    op.create_table('tournee',
    sa.Column('id_tournee', sa.Integer(), nullable=False),
    sa.Column('id_run', sa.Integer(), nullable=False),
    sa.Column('distance_totale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=12), nullable=False),
    sa.Column('date_calcul', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_station_depart', sa.Integer(), nullable=False),
    sa.Column('id_station_retour', sa.Integer(), nullable=False),
    sa.Column('id_chauffeur', sa.Integer(), nullable=False),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.CheckConstraint("statut IN ('planifiee','en_cours','terminee')", name='chk_tour_statut'),
    sa.ForeignKeyConstraint(['id_chauffeur'], ['chauffeur.id_chauffeur'], ),
    sa.ForeignKeyConstraint(['id_station_depart'], ['station.id_station'], ),
    sa.ForeignKeyConstraint(['id_station_retour'], ['station.id_station'], ),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicule.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_tournee')
    )
    op.create_table('affectation',
    sa.Column('id_affectation', sa.Integer(), nullable=False),
    sa.Column('ordre_visite', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('id_tournee', sa.Integer(), nullable=False),
    sa.Column('id_lot', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordre_visite > 0', name='chk_aff_ordre'),
    sa.CheckConstraint('quantite > 0', name='chk_aff_qte'),
    sa.ForeignKeyConstraint(['id_lot'], ['lot.id_lot'], ),
    sa.ForeignKeyConstraint(['id_tournee'], ['tournee.id_tournee'], ),
    sa.PrimaryKeyConstraint('id_affectation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affectation')
    op.drop_table('tournee')
    op.drop_table('vehicule')
    op.drop_table('lot')
    op.drop_table('chauffeur')
    op.drop_table('station')
    op.drop_table('destination')
    # ### end Alembic commands ###
